### ISSUE TITLE
Radv leading to panicked main thread in triangle example

### ISSUE THREAD

**Issue by Unmoving** [vulkano-rs/vulkano#387]
Running the triangle example code gives me:

`WARNING: radv is not a conformant vulkan implementation, testing use only.
Using device: AMD RADV POLARIS10 (type: DiscreteGpu)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Timeout', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837
note: Run with `RUST_BACKTRACE=1` for a backtrace.
`

I am not sure whether this is a RADV bug or one I could fix. Any ideas here? Will you test with Mesa/Radv as well?

**Comment by Unmoving** [comment]
Just fyi, it happens because of this line:

`375         let image_num = swapchain.acquire_next_image(Duration::new(1, 0)).unwrap();`

Now I changed it to:

`375         let image_num = swapchain.acquire_next_image(Duration::new(10, 0)).unwrap();`

and now the program runs for 10 seconds and then panics :(

**Comment by bytesnake** [comment]
I have the same problem on my Intel Ivy Bridge. The Vulkan driver is at the latest version 17.0.1-1, so everything should be fine, but at some point (after 20 loops or so) the timeout of acquire_next_image is reached and the program crashs.

```
WARNING: Ivy Bridge Vulkan support is incomplete
Using device: Intel(R) Ivybridge Mobile (type: IntegratedGpu)
anv_image.c:201: FINISHME: Implement HiZ for input attachments
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Timeout'
```

**Comment by DaseinPhaos** [comment]
@bytesnake
Due to the attached error message, this is clearly a problem caused by the Vulkan implementation of Ivy Bridge. Even a newest implementation *can* be incorrect or incomplete. You can see that `FINISHME` comment from the source code of Intel there...

Also, it is worth noting that it *is* valid for a Vulkan implementation to choose not to support some specific "feature"s of the Vulkan specification. I do agree that if this is the case, checking whether the required feature can be used beforehand ( and return a more comprehensible error message to the user if not) would be more appropriate for the example code.

I'm not 100% sure (because I don't know anything called "HiZ" relating to any Vulkan feature) but I think the problem you listed here is a bug from Intel. [See their discussions](https://patchwork.freedesktop.org/patch/141117/)

**Comment by bytesnake** [comment]
Mh, I'm certain that the triangle example is supposed to work, even on an Intel. I've tested the examples from https://github.com/SaschaWillems/Vulkan and everything is working just fine (except terraintessellation)

**Comment by ryndinol** [comment]
I'm also using radv, and have this problem with the triangle/teapot example. You can match on the error instead of unwrapping (as well as handle recreating the swapchain):

```rust
match swapchain.acquire_next_image(Duration::from_millis(1)) {
    Result::Ok(image_num) => {
        // Present triangle/teapot/etc.
    },
    Result::Err(err) => {
        vulkano::swapchain::AcquireError::OutOfDate => {
            recreate_swapchain = true;
        },
        err => println!("Swapchain acquire error: {}", err)
    }
}
```

However, this leads to a different panic:

```
Swapchain acquire error: no image is available for acquiring yet
dt: 0.334312 ms
Swapchain acquire error: no image is available for acquiring yet
dt: 0.560813 ms
Swapchain acquire error: no image is available for acquiring yet
dt: 0.455526 ms
thread 'main' panicked at 'assertion failed: index < len', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcollections/vec.rs:762
stack backtrace:
   1:     0x55697b246f8c - std::sys::imp::backtrace::tracing::imp::write::h23bcdb89e70c5bbf
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x55697b2494be - std::panicking::default_hook::{{closure}}::he7b82439fd2d2bb6
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x55697b2490c4 - std::panicking::default_hook::he1cd4269c1558f23
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/panicking.rs:367
   4:     0x55697b24995b - std::panicking::rust_panic_with_hook::h006b37e36b7c8982
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x55697b2497a4 - std::panicking::begin_panic::h043cddfdd3933cc4
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x55697b249719 - std::panicking::begin_panic_fmt::h34e588bba6b8a2c2
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/panicking.rs:501
   7:     0x55697b2496a7 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/panicking.rs:477
   8:     0x55697b273dbd - core::panicking::panic_fmt::he52644573ecd78ff
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x55697b273cf4 - core::panicking::panic::hab2712470c117667
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/panicking.rs:49
  10:     0x55697b166432 - <collections::vec::Vec<T>>::remove::h212820e650179e10
                        at /home/***/workspace/rs/vulkano/examples/<panic macros>:4
  11:     0x55697b1ca10d - vulkano::swapchain::swapchain::Swapchain::acquire_next_image::h31c02d06bbb4d191
                        at /home/***/workspace/rs/vulkano/vulkano/src/swapchain/swapchain.rs:285
  12:     0x55697b0a1563 - teapot::main::h988c9674ea919c4f
                        at /home/***/workspace/rs/vulkano/examples/src/bin/teapot.rs:345
  13:     0x55697b2503ea - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  14:     0x55697b249e66 - std::rt::lang_start::h1ef940195e3c010e
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/panicking.rs:436
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/panic.rs:361
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/rt.rs:57
  15:     0x55697b0ac7f2 - main
  16:     0x7f3f95b68f0f - __libc_start_main
  17:     0x55697af718b8 - _start
  18:                0x0 - <unknown>
```
It looks like in 
https://github.com/tomaka/vulkano/blob/master/vulkano/src/swapchain/swapchain.rs :285
a semaphore is removed form the pool, but never put back in if acquiring the image fails for any reason.

I don't know if this is a proper solution, but for messing around on amdgpu+radv, the semaphore can just be put back in:

```rust
    pub fn acquire_next_image(&self, timeout: Duration) -> Result<usize, AcquireError> {
        unsafe {
            let stale = self.stale.lock().unwrap();
            if *stale {
                return Err(AcquireError::OutOfDate);
            }

            let vk = self.device.pointers();

            let semaphore = self.semaphores_pool.lock().unwrap().remove(0);

            let timeout_ns = timeout.as_secs().saturating_mul(1_000_000_000)
                                              .saturating_add(timeout.subsec_nanos() as u64);

            let mut out = mem::uninitialized();
            let r = try!(check_errors(vk.AcquireNextImageKHR(self.device.internal_object(),
                                                             self.swapchain, timeout_ns,
                                                             semaphore.internal_object(), 0,     // TODO: timeout
                                                             &mut out)));

            let id = match r {
                Success::Success => out as usize,
                Success::Suboptimal => out as usize,        // TODO: give that info to the user
                Success::NotReady | Success::Timeout => {
                    self.semaphores_pool.lock().unwrap().push(semaphore);
                    return Err(AcquireError::Timeout)
                },
                s => panic!("unexpected success value: {:?}", s)
            };

            let mut images_semaphores = self.images_semaphores.lock().unwrap();
            images_semaphores[id] = Some(semaphore);

            Ok(id)
        }
    }
```

**Comment by tomaka** [comment]
Ah thanks for the investigation, I didn't think of this.
However this semaphore system has been completely removed in the `incoming` branch, so this problem will eventually fix itself.

**Comment by oblitum** [comment]
I think this is probably related, I'm on a 7700K on ArchLinux, using the Intel graphics solely. In all examples I get:

```
~/D/P/vulkano ❯❯❯ RUST_BACKTRACE=1 cargo run -p examples --bin triangle
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/triangle`
Using device: Intel(R) Kabylake GT2 (type: IntegratedGpu)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Timeout', /checkout/src/libcore/result.rs:859
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:737
   1: triangle::main
             at ./examples/src/bin/triangle.rs:375
```

The sample runs for about 1 second and ends with that.

**Comment by corngood** [comment]
```
WARNING: radv is not a conformant vulkan implementation, testing use only.
Using device: AMD RADV HAWAII (type: DiscreteGpu)
DS(ERROR): object: 0x7fca0fa33000 type: 6 location: 4356 msgCode: 6: Cannot submit cmd buffer using image (0x3) [sub-resource: aspectMask 0x1 array layer 0, mip level 0], with layout VK_IMAGE_LAYOUT_UNDEFINED when first use is VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL.
DS(ERROR): object: 0x7fca1921ad00 type: 4 location: 12233 msgCode: 1964: Images passed to present must be in layout VK_IMAGE_LAYOUT_PRESENT_SRC_KHR but is in VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL. For more information refer to Vulkan Spec Section '30.6. WSI Swapchain' which states 'Any given element of pImageIndices must be the index of a presentable image acquired from the swapchain specified by the corresponding element of the pSwapchains array, and the presented image subresource must be in the VK_IMAGE_LAYOUT_PRESENT_SRC_KHR layout at the time the operation is executed on a VkDevice' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/xhtml/vkspec.html#VkPresentInfoKHR)
DS(ERROR): object: 0x2 type: 27 location: 12416 msgCode: 102: vkAcquireNextImageKHR: Application has already acquired the maximum number of images (0x1)
DS(ERROR): object: 0x7fca12d59000 type: 6 location: 4356 msgCode: 6: Cannot submit cmd buffer using image (0x4) [sub-resource: aspectMask 0x1 array layer 0, mip level 0], with layout VK_IMAGE_LAYOUT_UNDEFINED when first use is VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL.
DS(ERROR): object: 0x7fca1921ad00 type: 4 location: 12233 msgCode: 1964: Images passed to present must be in layout VK_IMAGE_LAYOUT_PRESENT_SRC_KHR but is in VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL. For more information refer to Vulkan Spec Section '30.6. WSI Swapchain' which states 'Any given element of pImageIndices must be the index of a presentable image acquired from the swapchain specified by the corresponding element of the pSwapchains array, and the presented image subresource must be in the VK_IMAGE_LAYOUT_PRESENT_SRC_KHR layout at the time the operation is executed on a VkDevice' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/xhtml/vkspec.html#VkPresentInfoKHR)
DS(ERROR): object: 0x2 type: 27 location: 12416 msgCode: 102: vkAcquireNextImageKHR: Application has already acquired the maximum number of images (0x2)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Timeout', src/libcore/result.rs:845
```

As far as I can tell, there are no image transitions happening at all.  DESIGN.md mentions handling transitions automatically, but the only way I can see it happening is if you add `CmdPipelineBarrier` to an `UnsafeCommandBufferBuilder`.  Am I missing something?

I'm guessing other implementations just tolerate this?

**Comment by tomaka** [comment]
@corngood That's "on purpose". The branch I merged on master is better on some aspects but removed pipeline transitions. I didn't think this would lead to a timeout though :-/

**Comment by corngood** [comment]
Yeah, timeout is a strange reaction, but I guess all bets are off after the validation failures.

I don't think having to add the barriers is a problem.  The same triangle example in any other language would have them.  However, having to use the unsafe builder for the simplest example seems unfortunate.

I guess the plan is to use `AutoPipelineBarriersLayer`?

**Comment by tomaka** [comment]
This is not strictly related to the `AutoPipelineBarriersLayer`.
Right now vulkano supposes that newly-created images are already in the right layout, which is not the case.
Before the incoming merge, it would create and submit a command buffer that does the transition, but it's not a good solution to make things implicit like this.

Right now my idea is that when you create an image you receive (in addition to the image) a special object that implements `ImageAccess` and that should be used when you use the image for the first time. Failure to do so results in a runtime error (an AtomicBool is checked). You could also simply use that object to do the transition and wait for it to be performed in a synchronous way.

**Comment by corngood** [comment]
FYI I fixed the validation errors and I still get a timeout in `AcquireNextImageKHR`.  I have a very similar test written in C which doesn't show this behaviour, but I haven't tracked down what's different.

**Comment by corngood** [comment]
Ah, so I can stop the hang by either switching to FIFO presentation, or setting the timeout to `u64::max_value()`.  Using a finite timeout seems to result in some sort of deadlock in radv.  I'm not sure if there's something else we're doing wrong, but I can reproduce it in my C program, so I'm leaning toward a bug in radv.

**Comment by corngood** [comment]
So, I actually found a way to fix this in libxcb:

https://lists.freedesktop.org/archives/xcb/2017-April/011006.html

I'm waiting to hear if they think it's a legit bug there, or if it should be somehow fixed in mesa.

For the examples in vulkano, I'm thinking we should switch to FIFO presentation (guaranteed to be available), and use UINT64_MAX as a default timeout.  That would be consistent with the vulkan loader demo.

**Comment by tomaka** [comment]
> I'm thinking we should switch to FIFO presentation (guaranteed to be available)

The reason why this is not the case is that last time I checked the open source Intel driver isn't conformant and doesn't support FIFO.

**Comment by Ralith** [comment]
> last time I checked the open source Intel driver isn't conformant and doesn't support FIFO.

My Intel Linux driver reports via vulkaninfo:
```
Present Modes:          count = 3
        IMMEDIATE_KHR
        MAILBOX_KHR
        FIFO_KHR
```
Maybe this was fixed in mesa 17?

**Comment by tomaka** [comment]
Yeah it's probably fixed now.

**Comment by tomaka** [comment]
The Fifo thing has been changed by #514

**Comment by rukai** [comment]
Looks like these are old driver issues, I don't think any of these still occur.
